spring:
  config:
    import: "configserver:"
  application:
    name: cloud-config
  cloud:
    config:
      profile: prod
      uri: http://localhost:7070
      username: TU_USUARIO_GIT
      password: TU_CONTRASEÃ‘A_GIT


server:
  port: 8083